### ISSUE TITLE
MSA call final word

### ISSUE THREAD

**Issue by wpears** [higs4281/mapusaurus#4]
Hey Bill, so in addition to the lender filtering issue (meaning I think you should reopen #1 ), it might be wise to have separate data and geometry calls. This way we can turn on peers/change lender without pulling in geometries for the MSA we are looking at.

So this could either be two endpoints ie:
- api/msa/geo?...
- api/msa/data?...
  or a flag in the params ie:
- api/msa?geo=1...

Thanks!

**Comment by higs4281** [comment]
#1 fixed.

to clarify: you want the new data endpoint to deliver all the volume/peer/category data currently delivered via the 4-corner "all" query?

**Comment by wpears** [comment]
Please~!

**Comment by wpears** [comment]
re our conversation:

geo call _keeps_ volume (so drawing points doesn't depend on the data call)
- this **needs** to take into account peers (and anything else that changes volume returned)

**Comment by higs4281** [comment]
calls to /api/msa now honor peer selection, so if peers=true, tract geojson delivers volume for peers instead of target lender.
i rigged a way to make api/msa calls much faster by pre-rendering the simplified tract geometry for each msa. to use this, the management command 'bake_msa_tracts' needs to be run once to pre-render the simplified msa geometries. it takes about 10 minutes to run.
